@url = http://localhost:3333/meals
@sessionId = 4984d7d4-0761-49b5-b375-9b6aac5523e8

### create meal
POST {{url}} HTTP/1.1
Content-Type: application/json
Cookie: sessionId={{sessionId}}

{
  "name": "Foo",
  "description": "Bar",
  "date": "2025-12-26T23:31:29.670Z",
  "isInDiet": false
}

### list all meals
GET {{url}} HTTP/1.1
Cookie: sessionId={{sessionId}}

### get meal by id
GET {{url}}/07b0b09e-2fd9-400b-8bd7-12f7dc634394 HTTP/1.1
Cookie: sessionId={{sessionId}}

### update meal by id
PUT {{url}}/c66c655b-e57e-40cf-8ffe-162d0970ca6e HTTP/1.1
Content-Type: application/json
Cookie: sessionId={{sessionId}}

{
  "name": "Foo updated",
  "description": "Bar updated",
  "date": "2025-12-26T13:13:29.670Z",
  "isInDiet": true
}

### delete meal by id
DELETE {{url}}/07b0b09e-2fd9-400b-8bd7-12f7dc634394 HTTP/1.1
Cookie: sessionId={{sessionId}}
